// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbY0qYpyvZDZz-ULQpyyXEO41L_i5rssU',
    appId: '1:383763116692:web:4cb9bd5831173f3f4dfa81',
    messagingSenderId: '383763116692',
    projectId: 'appreciationapp-prod',
    authDomain: 'appreciationapp-prod.firebaseapp.com',
    storageBucket: 'appreciationapp-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqspSSCxvZBe1Bdie0X39aJanXfUVwHo',
    appId: '1:383763116692:android:452324b501a7f5864dfa81',
    messagingSenderId: '383763116692',
    projectId: 'appreciationapp-prod',
    storageBucket: 'appreciationapp-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChNeedGUnC-NzBPbc5FzPfeBtfPYa3e_w',
    appId: '1:383763116692:ios:255f70858b8cac814dfa81',
    messagingSenderId: '383763116692',
    projectId: 'appreciationapp-prod',
    storageBucket: 'appreciationapp-prod.firebasestorage.app',
    iosBundleId: 'com.example.appreciationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChNeedGUnC-NzBPbc5FzPfeBtfPYa3e_w',
    appId: '1:383763116692:ios:255f70858b8cac814dfa81',
    messagingSenderId: '383763116692',
    projectId: 'appreciationapp-prod',
    storageBucket: 'appreciationapp-prod.firebasestorage.app',
    iosBundleId: 'com.example.appreciationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbY0qYpyvZDZz-ULQpyyXEO41L_i5rssU',
    appId: '1:383763116692:web:cc3d0e9f3eda6b634dfa81',
    messagingSenderId: '383763116692',
    projectId: 'appreciationapp-prod',
    authDomain: 'appreciationapp-prod.firebaseapp.com',
    storageBucket: 'appreciationapp-prod.firebasestorage.app',
  );

}